coverage:
  precision: 5
  round: down
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        if_not_found: failure
    patch:
      default:
        target: 100%
        threshold: 0%
        if_not_found: failure
