args<-commandArgs(TRUE)
pkgload::load_all(args[[1]],quiet=TRUE);suppressPackageStartupMessages(library(dplyr))
con<-DBI::dbConnect(RSQLite::SQLite(),':memory:');src<-copy_to(con,tibble(g=NA_character_,v=1),'source')
options(marginplyr.audit_sql=TRUE)
ledger<-character()
trace('dbSendQuery',where=asNamespace('DBI'),tracer=quote(ledger <<- c(ledger,as.character(statement))),print=FALSE)
cat('CONSTRUCT\n');q<-summarize_with_margins(src,z=sum(v,na.rm=TRUE),.grouping=rollup(g),.margin_label=NULL,.sort='last',.id='id');print(ledger);ledger<-character()
cat('DIRECT\n');invisible(collect(q));writeLines(ledger);ledger<-character()
cat('FINITE\n');invisible(collect(q,n=1));writeLines(ledger);ledger<-character()
cat('COMPUTE\n');invisible(compute(q,name='report',temporary=FALSE,analyze=TRUE));writeLines(ledger)
untrace('dbSendQuery',where=asNamespace('DBI'));DBI::dbDisconnect(con)
