pkgload::load_all('variants/B-direct',quiet=TRUE);suppressPackageStartupMessages(library(dplyr))
for(temporary in c(FALSE,TRUE)) {
 con<-DBI::dbConnect(RSQLite::SQLite(),':memory:')
 source<-copy_to(con,tibble(g=c('a','b'),v=c(2,5)),'source')
 DBI::dbExecute(con,"ATTACH ':memory:' AS other")
 sentinel<-data.frame(g='keep',id=99L,total=-1)
 DBI::dbWriteTable(con,DBI::Id(schema='other',table='report'),sentinel)
 q<-summarize_with_margins(source,total=sum(v,na.rm=TRUE),.grouping=rollup(g),.id='id',.margin_label=NULL,.sort='last')
 cat('temporary',temporary,'dbExists bare',DBI::dbExistsTable(con,'report'),'\n')
 outcome<-tryCatch({m<-compute(q,name='report',temporary=temporary,overwrite=TRUE,analyze=FALSE);collect(m)},error=identity)
 print(outcome)
 print(DBI::dbGetQuery(con,"SELECT name FROM other.sqlite_master"))
 stopifnot(identical(DBI::dbReadTable(con,DBI::Id(schema='other',table='report')),sentinel))
 DBI::dbDisconnect(con)
};cat('PASS attached-only unrelated sentinel preserved for temporary FALSE/TRUE\n')
