pkgload::load_all('variants/B-direct',quiet=TRUE);suppressPackageStartupMessages(library(dplyr))
p<-tempfile(fileext='.sqlite');c<-DBI::dbConnect(RSQLite::SQLite(),p)
s<-copy_to(c,tibble(g=c('a','b'),v=c(2,5)),'source',temporary=FALSE)
DBI::dbExecute(c,'CREATE TABLE marker (v INTEGER)')
DBI::dbBegin(c);DBI::dbExecute(c,'INSERT INTO marker VALUES (42)')
q<-summarize_with_margins(s,z=sum(v,na.rm=TRUE),.grouping=rollup(g),.sort='last',.margin_label=NULL)
m<-compute(q,name='report',temporary=FALSE,in_transaction=TRUE,analyze=FALSE)
stopifnot(nrow(collect(m))==3)
DBI::dbCommit(c);DBI::dbDisconnect(c)
c<-DBI::dbConnect(RSQLite::SQLite(),p)
stopifnot(identical(DBI::dbReadTable(c,'marker')$v,42L),nrow(DBI::dbReadTable(c,'report'))==3)
DBI::dbDisconnect(c);unlink(p);cat('PASS caller commit persists marker and result after reconnect\n')
