pkgload::load_all('/private/tmp/marginplyr-sqlite-design-20260925/variants/A',quiet=TRUE);suppressPackageStartupMessages(library(dplyr))
con<-DBI::dbConnect(RSQLite::SQLite(),':memory:');on.exit(DBI::dbDisconnect(con));src<-copy_to(con,tibble(g=c('a','b'),v=c(2,5)),'source',temporary=FALSE)
DBI::dbExecute(con,"ATTACH DATABASE ':memory:' AS other")
old<-data.frame(old=17L);sentinel<-data.frame(g='sentinel',id=99L,total=-1);DBI::dbWriteTable(con,'report',sentinel);DBI::dbWriteTable(con,DBI::Id(schema='other',table='report'),old)
q<-summarize_with_margins(src,total=sum(v,na.rm=TRUE),.grouping=rollup(g),.id='id',.sort='last');DBI::dbBegin(con);DBI::dbExecute(con,'CREATE TABLE caller_marker(x INT)')
err<-tryCatch(compute(q,name=DBI::Id(schema='other',table='report'),temporary=FALSE,overwrite=TRUE,indexes=list('g')),error=identity)
stopifnot(inherits(err,'error'),identical(DBI::dbReadTable(con,'report'),sentinel),identical(DBI::dbReadTable(con,DBI::Id(schema='other',table='report')),old),DBI::dbExistsTable(con,'caller_marker'),!any(grepl('^marginplyr_order_',DBI::dbListTables(con))))
DBI::dbRollback(con);stopifnot(!DBI::dbExistsTable(con,'caller_marker'));cat('PASS qualified index failure rolls back only own work; old destination + other schema + caller transaction preserved\n')
m<-compute(q,name=DBI::Id(schema='other',table='report'),temporary=FALSE,overwrite=TRUE,analyze=TRUE);stopifnot(nrow(collect(m))==3L,identical(DBI::dbReadTable(con,'report'),sentinel));cat('PASS subsequent qualified overwrite/analyze succeeds\n');print(DBI::dbGetQuery(con,'SELECT * FROM other.sqlite_stat1'))
